name: Compilar APK Flet

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Copiar repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar dependencias del sistema y Flet
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git libltdl-dev
        pip install --upgrade pip
        pip install flet buildozer

    - name: Compilar APK con Buildozer
      run: |
        flet build apk

    - name: Subir APK como artefacto
      uses: actions/upload-artifact@v4
      with:
        name: app-apk
        path: bin/*.apk