name: Build APK
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build with Buildozer
        uses: sashahilton00/buildozer-action@v1
        with:
          repository: .
          buildozer_version: stable
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
