name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo-dev cmake libffi-dev libssl-dev

      - name: Prepare Android Environment and Accept Licenses
        run: |
          # Crear directorios necesarios para el SDK
          mkdir -p $HOME/.android
          touch $HOME/.android/repositories.cfg
          
          # Instalar herramientas de línea de comandos si fuera necesario y aceptar licencias
          # El comando 'yes' responde 'y' automáticamente a todas las solicitudes de licencia
          yes | sdkmanager --licenses || true

      - name: Build with Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer
          # Ejecutar compilación asegurando el entorno
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: bin/*.apk
